config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bullshit, only: :index
  root :to => redirect('/bullshit')

  get 'sign-up',  to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'

  get 'sign-in',  to: 'authentications#new'
  post 'sign-in', to: 'authentications#create'
  get 'sign-out', to: 'authentications#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    "#{first_name} #{last_name}".titleize
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end

  def require_login
    unless current_user
      flash[:danger] = "You must sign in"
      redirect_to sign_in_path
    end
  end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(first_name: params[:first_name], last_name: params[:last_name])
    if user. != nil
      session[:user_id] = user.id
      flash[:notice] = 'You have successfully signed in'
      redirect_to bullshit_index_path
    else
      flash[:notice] = 'Email / Password combination is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    session[:return_to] = nil
    flash[:notice] = 'You have successfully logged out'
    redirect_to sign_in_path
  end

end

app/controllers/bullshit_controller.rb
class BullshitController < ApplicationController
  before_action :require_login

  def index
    @users = User.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'You have successfully signed up'
      redirect_to bullshit_index_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentications/new.html.erb
<%= form_tag sign_in_path do |f| %>
  <!-- <p>
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </p> -->

  <p>
    <%= label_tag :first_name %>
    <%= text_field_tag :first_name %>
  </p>

  <p>
    <%= label_tag :last_name %>
    <%= text_field_tag :last_name %>
  </p>

  <p>
    <%= submit_tag "Sign In" %>
  </p>

<% end %>

app/views/bullshit/index.html.erb
<!--  -->

<h1>YOU SHOULD ONLY SEE THIS PAGE AFTER YOU'VE LOGGED IN</h1>

<% @users.each do |user| %>
  <li> <%= user.full_name %> </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HatchDeviseApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <% if current_user %>
    <%= current_user.full_name %>
    <%= link_to 'Sign Out', sign_out_path %>
  <% else %>
    <%= link_to 'Sign In', sign_in_path %>
    <%= link_to 'Sign Up', sign_up_path %>
  <% end %>

<%= yield %>

</body>
</html>